# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               trungjann
tagline:             'Tôi rất rảnh, bạn cũng thế'
description:         'Một blog <a href="http://jekyllrb.com" target="_blank">Jekyll</a> đơn giản được tạo bởi con người lần đầu biết code trông thế nào, các bạn đừng mong đợi nhiều.'
url:                 http://trungjann.github.io
baseurl:             ''
paginate:            5

excerpt_separator: '<br>'

# About/contact
# author:
#  name:              
#  url:               
#  email:             

# Custom vars
version:             1.0.0
