# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               trungjann
tagline:             'Rảnh rỗi sinh nông nổi'
description:         'Một blog <a href="http://jekyllrb.com" target="_blank">Jekyll</a> đơn giản, dựa trên theme sẵn có của <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://trungjann.github.io
baseurl:             ''
paginate:            5

# About/contact
# author:
#  name:              
#  url:               
#  email:             

# Custom vars
version:             1.0.0
